### ISSUE TITLE
Missing journey PDFs

### ISSUE THREAD

**Issue by frarin** [Azure-Samples/zero2hero#1]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

We only have 3 journey PDFs, and the links for the others obviously aren't working.

<img width="766" alt="image" src="https://github.com/Azure-Samples/zero2hero/assets/98345119/1d16837a-b4dd-4d2d-a982-f6340f0c9d30">

<img width="234" alt="image" src="https://github.com/Azure-Samples/zero2hero/assets/98345119/8fa38518-eed5-4a1a-9e08-fe34a77a69e7">

**Comment by olivMertens** [comment]
👍🏻

**Comment by vieiraae** [comment]
The other journeys are work in progress. Stay tuned

**Comment by vieiraae** [comment]
closing the issue. the journeys will be revamped to another format
